/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WONGHASADORN2
 */
public class normalMode extends javax.swing.JFrame {

    /**
     * Creates new form normalMode
     */
    int[] score={0,0,0};
    int round =1;
    int hideshow =1;
    public normalMode() {
        initComponents();
        winField.setText(Integer.toString(score[0]));
        loseField.setText(Integer.toString(score[1]));
        drawField.setText(Integer.toString(score[2]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlayerChoose = new javax.swing.JLabel();
        ComputerChoose = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RockButton = new javax.swing.JButton();
        PaperButton = new javax.swing.JButton();
        ScissorsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Log = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        winField = new javax.swing.JTextField();
        loseField = new javax.swing.JTextField();
        drawField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemBack = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        PlayerChoose.setText("Your weapon");

        ComputerChoose.setText("Enemy weapon");

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayerChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(ComputerChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComputerChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(PlayerChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        RockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rock25.png"))); // NOI18N
        RockButton.setText("Rock");
        RockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RockButtonActionPerformed(evt);
            }
        });

        PaperButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paper25.png"))); // NOI18N
        PaperButton.setText("Paper");
        PaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperButtonActionPerformed(evt);
            }
        });

        ScissorsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scissors25.png"))); // NOI18N
        ScissorsButton.setText("Scissors");
        ScissorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScissorsButtonActionPerformed(evt);
            }
        });

        Log.setColumns(20);
        Log.setRows(5);
        jScrollPane1.setViewportView(Log);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScissorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScissorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("WLD");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setText("Win");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setText("Lose");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setText("Draw");

        winField.setEditable(false);
        winField.setText("0");

        loseField.setEditable(false);
        loseField.setText("0");

        drawField.setEditable(false);
        drawField.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(winField)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loseField)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawField)
                        .addGap(17, 17, 17))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addComponent(drawField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(winField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loseField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jMenu1.setText("Control");

        jMenuItem1.setText("NewGame");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItemBack.setText("Back");
        jMenuItemBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBackActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBack);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem2.setText("Build by Inroger");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("FB: Parinya Wonghasadorn");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBackActionPerformed
        // TODO add your handling code here:
        new mainManu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemBackActionPerformed

    private void RockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RockButtonActionPerformed
        // TODO add your handling code here:
        PlayerChoose.setText("ROCK");
        PlayerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rock25.png")));
    int comC = (int) (Math.random()*3);
        if ( comC == 0){
            ComputerChoose.setText("ROCK");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rock25.png")));
            result.setText("DRAW");
            score[2]=score[2]+1;
            Log.append(round+" Player Rock |DRAW| Computer Rock. \n");
            round++;
        }else if(comC == 1){
            ComputerChoose.setText("PAPER");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paper25.png")));
            result.setText("WIN");
            score[1]=score[1]+1;
            Log.append(round+" Player Rock |WIN| Computer Paper. \n");
            round++;
        }else if(comC == 2){
            ComputerChoose.setText("SCISSORS");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scissors25.png")));
            result.setText("LOSE");
            score[0]=score[0]+1;
            Log.append(round+" Player Rock |LOSE| Computer Scissors. \n");
            round++;
        }
        updateScore();
    }//GEN-LAST:event_RockButtonActionPerformed

    private void PaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperButtonActionPerformed
        // TODO add your handling code here:
        PlayerChoose.setText("PAPER");
        PlayerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paper25.png")));
    int comC = (int) (Math.random()*3);
        if ( comC == 0){
            ComputerChoose.setText("ROCK");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rock25.png")));
            result.setText("WIN");
            score[0]=score[0]+1;
            Log.append(round+" Player Paper |WIN| Computer Rock. \n");
            round++;
        }else if(comC == 1){
            ComputerChoose.setText("PAPER");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paper25.png")));
            result.setText("DRAW");
            score[2]=score[2]+1;
            Log.append(round+" Player Paper |DRAW| Computer Paper. \n");
            round++;
        }else if(comC == 2){
            ComputerChoose.setText("SCISSORS");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scissors25.png")));
            result.setText("LOSE");
            score[1]=score[1]+1;
            Log.append(round+" Player Paper |LOSE| Computer Scissors. \n");
            round++;
        }
        updateScore();
    }//GEN-LAST:event_PaperButtonActionPerformed

    private void ScissorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScissorsButtonActionPerformed
        // TODO add your handling code here:
        PlayerChoose.setText("SCISSORS");
            PlayerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scissors25.png")));
    int comC = (int) (Math.random()*3);
        if ( comC == 0){
            ComputerChoose.setText("ROCK");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rock25.png")));
            result.setText("LOSE");
            score[1]=score[1]+1;
            Log.append(round+" Player Scissors |LOSE| Computer Rock. \n");
            round++;
        }else if(comC == 1){
            ComputerChoose.setText("PAPER");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paper25.png")));
            result.setText("WIN");
            score[0]=score[0]+1;
            Log.append(round+" Player Scissors |WIN| Computer Paper. \n");
            round++;
        }else if(comC == 2){
            ComputerChoose.setText("SCISSORS");
            ComputerChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scissors25.png")));
            result.setText("DRAW");
            score[2]=score[2]+1;
            Log.append(round+" Player Scissors |DRAW| Computer Scissors. \n");
            round++;
        }
        
        updateScore();
    }//GEN-LAST:event_ScissorsButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        score[0]=0;
        score[1]=0;
        score[2]=0;
        Log.setText("");
        round =1;
        updateScore();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(normalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(normalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(normalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(normalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new normalMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComputerChoose;
    private javax.swing.JTextArea Log;
    private javax.swing.JButton PaperButton;
    private javax.swing.JLabel PlayerChoose;
    private javax.swing.JButton RockButton;
    private javax.swing.JButton ScissorsButton;
    private javax.swing.JTextField drawField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loseField;
    private javax.swing.JLabel result;
    private javax.swing.JTextField winField;
    // End of variables declaration//GEN-END:variables

    
    private void updateScore() {
        winField.setText(Integer.toString(score[0]));
        loseField.setText(Integer.toString(score[1]));
        drawField.setText(Integer.toString(score[2]));
    }

}
